// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(AccountDBContext))]
    [Migration("20221030070328_MIGRATIONNAME")]
    partial class MIGRATIONNAME
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication2.Models.AccountingFinance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("EmployeeSalary")
                        .HasColumnType("float");

                    b.Property<double>("OfficeRentprice")
                        .HasColumnType("float");

                    b.Property<double>("OfficeSupplyPrice")
                        .HasColumnType("float");

                    b.Property<double>("SoldSWPrice")
                        .HasColumnType("float");

                    b.Property<double>("TaxPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AccountingFinances");
                });
#pragma warning restore 612, 618
        }
    }
}
